### ISSUE TITLE
more documentation!!

### ISSUE THREAD

**Issue by evancasey** [sleexyz/hylogen#23] opened 2016-04-12 21:38 UTC

**Comment by evancasey** [comment] 2016-04-12 21:38
[![selfie-0](http://i.imgur.com/2ZdsRZ7.png)](https://github.com/thieman/github-selfies/)

**Comment by evancasey** [comment] 2016-04-12 21:43
[![selfie-0](http://i.imgur.com/l7LHGN6.png)](https://github.com/thieman/github-selfies/)

**Comment by sleexyz** [comment] 2016-05-02 07:04
duplicate of #5 .

_let these photos be hidden away in depths of the githubs..._

**Closed as completed by sleexyz** 2016-05-02 07:04 UTC
